# Config for accuracy benchmark
models:
  # Enable or disable specific models
  - name: llama_guard
    enabled: true
    
  - name: protectai
    enabled: true
    
  - name: deepset
    enabled: true
    
  - name: katanemo
    enabled: true
    
  - name: xgboost
    enabled: true

# System Settings
settings:
  # We aren't testing speed, so we can make it faster
  # Use MPS for Mac systems with Apple Silicon
  # @todo change to 'cuda' if using GPU on other systems
  device: 'mps'
  
  fp16: false # this may lower accuracy for some models

logging:
  # We obviously need this
  stats: true
